### ISSUE TITLE
قابلیت های بیشتر

### ISSUE THREAD

**Issue by Morghak963** [azavaxhuman/MarzbanInboundGenerator#1]
سلام خسته نباشید
اگر‌ممکن هست کانفیگ ها رو بشه با جزئیات بیشتری ساخت 
مثلا ست کردن alpn یا utls و یا multi mode برای grpc

با تشکر🌹

**Comment by mahsamcse** [comment]
با درود
واقعا تشکر میکنم از این جنریتور خوب و کاربردی
منم موافقم با پیشنهاد این دوستمون
مثلا Dokodemo-door هم جاش خالیه

و یه پیشنهاد دیگه
اگه لطف کنید این ابزار رو توسعه بدین تا در تکمیل کردن قسمت های outbounds و routing هم بشه ازش کمک گرفت خیلی عالی میشه
مثلا برای تانل کردن پنل به پنل یا فعال کردن وارپ و یا مسدود سازی سایت های ایرانی و از این قبیل دست کاری ها که باید دستی توی x-ray انجام بدیم
با تشکر
