### ISSUE TITLE
درخواست آپدیت

### ISSUE THREAD

**Issue by m-mjd** [azavaxhuman/MarzbanInboundGenerator#3]
با عرض سلام و وقت بخیر خدمت شما 

پروتکل های زیادی اضافه شده به xray و خب خیلی از دوستان نمیتونن ازشون استفاده کنن چون اطلاعات کافی راجع به اینباندشو ندارن
اگه امکان اپدیت اسکریپت رو داشته باشید خیلی خوب میشه که پروتکل های جدید رو هم مد نظر بگیرید
تشکر

**Comment by RelaxStation** [comment]
Kcp transport (https://github.com/Gozargah/Marzban/commit/04b75f610317867fd9876ee28dfda1378d39f481)
Add multi mode for grpc (https://github.com/Gozargah/Marzban/commit/12b21b14f87ee2f49f80359f1ca2ce7a77dd5f44)
Support gRPC Custom Path (https://github.com/Gozargah/Marzban/commit/dae8eb8130b8e5bf3c6ed92918fbd2c64cd05202)
Wireguard
and so many new features
Thanks a lot ♥
